imap:
    - emailparam:
        userid : wim@ttvn.nl
        password : Ww
        host: server72.hosting2go.nl
        port: 993
    - emailparam:
        userid : wim@kielen.nl
        password : Qc
        host: imap.freedom.nl
        port: 993