imap:
    - emailparam:
        userid : secretaris@ttvn.nl
        password : TTVN4all!
        host: server72.hosting2go.nl
        port: 993
    - emailparam:
        userid : wim@kielen.nl
        password : Queen_0000
        host: imap.vevida.com
        port: 993